global:
  scrape_interval: 1m
  scrape_timeout: 10s
  evaluation_interval: 1m
scrape_configs:
  - job_name: push-gateway
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - pushgateway:9091
