steps:
  - label: ":nix::point_right::pipeline:"
    command: |
      nix eval --impure --json --expr '(import ./.buildkite { pipeline = ./.buildkite/pipeline.nix; })' \
      | buildkite-agent pipeline upload --no-interpolation
    agents:
      queue: project42
    timeout_in_minutes: 60
