# Please, don't use any default port allocations.
# https://github.com/prometheus/prometheus/wiki/Default-port-allocations
global:
  scrape_interval: 1m
  scrape_timeout: 10s
  evaluation_interval: 1m
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 5s
  scrape_timeout: 5s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - promethues:9090
    labels:
      alias: prometheus
- job_name: node
  honor_timestamps: true
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - mantis:13798
    labels:
      alias: mantis-node
- job_name: akka
  honor_timestamps: true
  scrape_interval: 10s
  scrape_timeout: 10s
  scheme: http
  static_configs:
    - targets:
        - mantis:9095
      labels:
        alias: mantis-akka-node

